<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net35;net8.0</TargetFrameworks>
    <AssemblyName>GunGameArena.Core</AssemblyName>
    <RootNamespace>GunGameArena.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net35'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net35" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
