<Project>
  <PropertyGroup>
    <H3VR_DIR Condition="'$(H3VR_DIR)' == ''">C:\Program Files (x86)\Steam\steamapps\common\H3VR</H3VR_DIR>
    <H3VR_PROFILE_DIR Condition="'$(H3VR_PROFILE_DIR)' == ''">$(APPDATA)\Thunderstore Mod Manager\DataFolder\H3VR\profiles\Default\BepInEx</H3VR_PROFILE_DIR>
    <H3VR_MANAGED>$(H3VR_DIR)\h3vr_Data\Managed</H3VR_MANAGED>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
</Project>
